### ISSUE TITLE
The sound is the same for boost, standby, sleep modes.

### ISSUE THREAD

**Issue by vlk3ru** [deividAlfa/stm32_soldering_iron_controller#108]
The sound is the same for boost, standby, sleep modes. Sometimes, when working without looking at the display, the same sound leads to errors. Dear author, could you make them different?

**Comment by deividAlfa** [comment]
Not sure if this subject deserves any effort? It only needs a quick peek to the display when it beeps.
Maybe a long beep for any low-power mode and a normal beep for the run/boost mode.

If you thought the sound frequency could be changed, well, you can't, it can only be enabled or disabled.

**Comment by vlk3ru** [comment]
Example:
boost - long sound it's high temperature.
standby - short sound.
sleep - two short sounds.

**Comment by vlk3ru** [comment]
Sometimes when you press a tight encoder, a random rotation occurs. And instead of standby I get boost.

**Comment by deividAlfa** [comment]
That's what cheap encoders do, I can't do anything

**Comment by vlk3ru** [comment]
I ordered this type of encoders, but they are even tougher. :(

**Comment by deividAlfa** [comment]
Don't buy Aliexpress encoders! Genuine Bourns are cheap enough, $2 or less!
I made a workaround, so if a click is issued very quickly after the iron working was changed by the button, it will revert the working mode and enter sleep.

Still, not the proper solution. Crappy encoders can behave very erratically, I can't make 1000 worarounds.

**Comment by deividAlfa** [comment]
Try v1.13.7.
The handling should be better now,  but might not be perfect.
As I said I bad encoders are bad encoders, can't be fixed, only mitigated.

Also, take great care when soldering new encoders, they're very sensitive to heat, don't apply heat for more than 2-3 seconds, the plastic internals will deform with heat and cause all kind of issues.

**Comment by vlk3ru** [comment]
Ok. Thanks you.
