### ISSUE TITLE
porting to Handskit Mini Rework Station

### ISSUE THREAD

**Issue by Careless** [deividAlfa/stm32_soldering_iron_controller#111]
is there the possibility to port this firmware over to a Handskit Micro Rework Station firmware?

https://www.aliexpress.com/item/1005002890887241.html

It uses the same interface and I believe it uses a similar STM32 LCD expansion board for the display and control software, but the calibration is limited and requires an external temp sensor to dial in the hot-air temp accurately.

It only needs a software mod to be a much better portable 868D based rework kit.

**Comment by deividAlfa** [comment]
I don't have the hardware, I can't.

**Comment by Careless** [comment]
i figured. it's a good little unit if you're thinking of picking one up!

**Comment by deividAlfa** [comment]
I'm fine with my 858D!

**Comment by deividAlfa** [comment]
Closed, I will not buy new hardware to support elses's. If you want support, consider donating.
