### ISSUE TITLE
quecoo t12-955 nothing in display after flashing firmware

### ISSUE THREAD

**Issue by jducifuentes** [deividAlfa/stm32_soldering_iron_controller#12]
I just downloaded 

`https://github.com/deividAlfa/stm32_soldering_iron_controller/blob/master/BOARDS/Quicko/STM32F103/STM32SolderingStation.bin`

and flashed with stm32cube but nothing displays after reboot controller. Using backup from repo works well so wiring st-link I suppose is ok.

![IMG_4324](https://user-images.githubusercontent.com/45316074/137129769-12c66cc8-ea3e-484c-8987-80a1bb9206c7.JPG)

![IMG_4323](https://user-images.githubusercontent.com/45316074/137129786-52281ee3-0fcd-4d3d-8f03-1f109066e677.JPG)

**Comment by deividAlfa** [comment]
You're using the wrong firmware, read the [Readme](https://github.com/deividAlfa/stm32_soldering_iron_controller#compatibility) carefully.
The correct firmware for the 955 is
[**KSGER v2.x, JCD T12, QUECOO T12-955** ](https://github.com/deividAlfa/stm32_soldering_iron_controller/raw/master/BOARDS/KSGER/%5Bv2%5D/STM32F101/STM32SolderingStation.bin),  it's the same as Ksger v2.

Not Quicko F103 firmware.

**Comment by jducifuentes** [comment]
OMG sorry..... Working now ...

gracias tron

**Comment by deividAlfa** [comment]
Enjoy the firmware 👍
Issue closed.
