### ISSUE TITLE
Add support for Hakko FH200-01 Stand Sleep?

### ISSUE THREAD

**Issue by T-622** [deividAlfa/stm32_soldering_iron_controller#125]
Hi, was wondering if it was somehow possible to add support for stand sleep with Hakko FH200-like stands, where a 2-pin tilt switch is closed to enable sleep mode. I wired up a GX12 connector to an FM2027 handle and use it for the T12 handle. How could I make this possible?

**Comment by deividAlfa** [comment]
Can be done, read about Stand Mode in the operation manual.

**Comment by T-622** [comment]
Understood, thanks. Could not find it originally but fixed now.
