### ISSUE TITLE
KSGER v3 board overheat and keep in reboot loop

### ISSUE THREAD

**Issue by Unitarian** [deividAlfa/stm32_soldering_iron_controller#13]
Hello,

I would like to thank you for your great efforts for this awesome firmware. I downloaded this firmware image to my KSGER v3 station successfully, but when setting up the first run values. the iron tip starts heating up to 180 degrees (the default min value) and stays there. If i try to increase the temperature the system reboots and the back of the board becomes very hot to touch. near the mosfet/mcu area.

I got the stm32f103cbu6 variant.

any suggestions?

Thank you

**Comment by Unitarian** [comment]
The issue got resolved by setting low lcd contrast value below 3. I guess high contrast number overloads the voltage regulator, so it fails powering the mcu causing it to reset.

**Comment by deividAlfa** [comment]
It's probably the LDO regulator. Some Ksger use a linear regulator to convert 24V to 3.3V.
That generates a lot of heat, it's a common issue.
Lowering the contrast also reduces the current, that seems the regulator is at the very limit.
The best would be modifying the board, there're very small DC/DC modules in AliExpress/eBay, I'd use on these to step down 24V to 5V, and feed that to the regulator to get 3.3v, that way the heat will be greatly reduced.
<Img src="https://img.joomcdn.net/ccb69411b17f1dfb7ea884faf2350a9387c81bf9_original.jpeg" />
