### ISSUE TITLE
Проблема с энкодером на KSGER v3.x 

### ISSUE THREAD

**Issue by Alex-TV** [deividAlfa/stm32_soldering_iron_controller#14]
GhbПри прокручивании энкодера в одну сторону, курсор в меню сначала идет в верном направлении, после меняет направление. Также это замечено при изменении любых параметров. Если вращать медленно по одному щелчку, проблемы нет. Но стоит немного увеличить скорость вращения проблема повторяется.

**Comment by deividAlfa** [comment]
Is the original fw working correctly?
Nobody has complained about this, ever.
Might be a defective rotary encoder? Resolder the stm32 pins.

**Comment by Alex-TV** [comment]
Worked correctly. On old firmware. I'll check the contacts stm32. Zero calibration is also not clear. Incorrect NTC temperature. We managed to establish the correct temperature, only the selection of resistance in the settings. Did I load the firmware in the STM32 incorrectly? Didn't clear more than 64Kb memory.

**Comment by deividAlfa** [comment]
But you have to follow the instructions. It clearly states that you should clear the first 126KB.
If the programming didn't fail, I guess it was OK.
For the zero calibration, check the operation manual, it's pretty straightforward.
If your board has a different NTC or pullup resistor, report that. The firmware is adjusted to what users have reported, I don't have any Ksger myself.

**Comment by Alex-TV** [comment]
There is a 4.7K on  3.3V pullup resistor. After the resistor 4.7 kOhm goes to STM32. Board version STM32_T12_oled_v3.0.jpg R14  pullup resistor. R15 on STM32.

**Comment by Alex-TV** [comment]
Thanks, I fixed it. The Chinese pen contains a 15 kΩ thermistor. In the native 10kOhm. After soldering, the encoder started working. Although sometimes there are refunds.

**Comment by deividAlfa** [comment]
You have to measure the thermistor at 25°C.
Resolder all stm32 pins to ensure...
Sometimes there're also shorts, all those problems come from the bad quality at the factory...
