### ISSUE TITLE
Fixed room temperature.

### ISSUE THREAD

**Issue by porlock** [deividAlfa/stm32_soldering_iron_controller#140]
deividAlfa, does room temperature is taking into account in calculations for tip temp ? if yes it would be beneficial to add an option manually set room temperature in firmware, my NTC change in -+ 20C depends on electronic heat up, but my actual room temperature is always in 5C change range, i i could just set it fixed as 24C and error would always less than 3C. Not like now .. when using NTC measurement it can change from 20C to 40C, don't mention about that NTC sensors need to be calibrated to give precise readings.

**Comment by deividAlfa** [comment]
It's not room temperature, but the cold side of the tip, normally in the handle, where the thermocouple ends.
Search cold junction compensation.

**Comment by porlock** [comment]
Yes I know but cold side is actually in balance with room temperature, and for example jbc don't have sensor in handle. There is an option to connect  NTC sensor directly on controller board, but because electronic heats up it's not in balance with environment temperature, and actually makes more harm than good. Would be great to have possibility to set it fixed value.

**Comment by deividAlfa** [comment]
I repeat it's not the room temperature!
Have you tested the actual temperature drift?

**Comment by porlock** [comment]
Yes, when I installed ntc on control PCB it's more or less correct when I turn it on, like 22C after 30min it's 45C
