### ISSUE TITLE
Add instruction to disable write protection to readme

### ISSUE THREAD

**Issue by asdfire1** [deividAlfa/stm32_soldering_iron_controller#16]
I don't have any experience with stlink and this sort of stuff. I wanted to flash my KSGER station and was getting this message on the station screen:
"flash error system halted use btn to reset"

I tried flashing it multiple times but it would not work. 
I solved it by going to target > option bytes and disabling the write and read protections there. It may be good to add something about this to the readme in case anyone else gets this problem in the future.

**Comment by deividAlfa** [comment]
Ok, added [Programming](https://github.com/deividAlfa/stm32_soldering_iron_controller/blob/master/Readme_files/Programming.md) section in the Readme.
