### ISSUE TITLE
PID autotuning?

### ISSUE THREAD

**Issue by byteborg** [deividAlfa/stm32_soldering_iron_controller#18]
Would it be feasible to do some PID autotuning as in 3D printer firmwares?
Example: Marlin
https://github.com/MarlinFirmware/Marlin/blob/75b4ff9c98ab8de65bcb70b457c7176fb77e0fb1/Marlin/src/module/temperature.cpp#L564

**Comment by deividAlfa** [comment]
Sorry, this project is pretty much finished, just some small enhancements / fixes from time to time, but that's all, at least for while, can't spend lots of time in it.
The PID autotuning would be hard to achieve, as the tip thermal load will be changing depending on the soldering tip, parts and pcb (Unlike a heated bed and extruder, which is more constant), also the soldering heats up much faster than a 3d printer.
Will definitely take quite a lot of work and testing.
Anyone having the time and patience to contribute will be welcome.

Closing for the said reasons!
