### ISSUE TITLE
KSGER Hot Air 1.02 Request for Custom Firmware

### ISSUE THREAD

**Issue by magbuhosjames** [deividAlfa/stm32_soldering_iron_controller#20]
Custom fimware for KSGER T12 Soldering Station was great! KSGER also have a Hot Air Station that runs on STM32 chip, could you possible create a custom firmware for this. I may be happy to be the tester for this project.

PS. I don't know where to contact you, so I posted here in 'issues' section.

**Comment by deividAlfa** [comment]
Hello, not on my current plans, sorry!
Closing.
