### ISSUE TITLE
Iron Min Max limits always Celsius

### ISSUE THREAD

**Issue by TheStrath** [deividAlfa/stm32_soldering_iron_controller#22]
iron_screen.c does not consider tempUnit setting when limiting min and max value. May be others

**Comment by deividAlfa** [comment]
The temperature unit can be only changed in system_screen.c (Which does consider this).
iron_screen.c takes the current settings.
In it, you can change temps, timeouts... but not the temperature unit.
So why is it needed? Why are you reporting **no** issue at all?

**Comment by TheStrath** [comment]
Steps to recreate one instance of the issue:
System: Temperature: Set to degrees C
Iron: Max Temp: set to 480 degrees C
System:  Temperature: Set to degrees F
Iron: Max temp display reads 900 degrees F
Adjust value, Max limited to 480 degrees F

Confirmation:
System: Temperature: Set back to degrees C
Iron: Max temp display reads 250 degrees C

**Comment by deividAlfa** [comment]
Thanks. Now it's a proper bug report, explaining the issue itself.
Will check it and update soon.

**Comment by deividAlfa** [comment]
Fixed. Use the binaries from Release v1.0:
https://github.com/deividAlfa/stm32_soldering_iron_controller/releases/tag/v1.0
