### ISSUE TITLE
HARD FAULT

### ISSUE THREAD

**Issue by Geksagen** [deividAlfa/stm32_soldering_iron_controller#23]
Hello. I compiled your firmware from sources and flashed the microcontroller of the Ksger soldering station. After turning on the soldering station, the screen shows an error HARD FAULT SYSTEMS HALTED Use btn then reset. Board version 2, processor STM32F101CBT6. Compiled the firmware using STM32CubeIDE 1.9.0. The code hasn't changed. There is no such problem with the firmware laid out in the releases. What could be the problem?
[ksgerV2.zip](https://github.com/deividAlfa/stm32_soldering_iron_controller/files/8990163/ksgerV2.zip)

**Comment by deividAlfa** [comment]
Should be fixed by now, re-open this ticket if not.
