### ISSUE TITLE
OpenOCD flashing

### ISSUE THREAD

**Issue by Pelado-Mat** [deividAlfa/stm32_soldering_iron_controller#28]
Hi/Hola!
       I think that you reverted the merge that enables programming via openOCD for the linux users. Did you find a problem or it was a mistake?

**Comment by deividAlfa** [comment]
Oops sorry, yes, I forgot to refresh my local repo, then updated the code, accidentally overwriting it...
Please push it again!

**Comment by Pelado-Mat** [comment]
Created the new pull request! #29
