### ISSUE TITLE
Unknown Board rev. v2 / v3 mixup

### ISSUE THREAD

**Issue by kinoX51** [deividAlfa/stm32_soldering_iron_controller#31]
I've just ordered from the "KSGER Official Store" of AE an "KSGER STM32 V 3,1"
Unfortunately it came delivered with an MM32Spin, which is incompatible with your custom firmware.

I came across your eevblog-forum post (https://www.eevblog.com/forum/reviews/stm32-oled-digital-soldering-station-for-t12-handle/msg4286710/#msg4286710), that it is possible to replace the mm32 with an genuine stm32.

My problem is, that I can't tell which version of solderingstation I got.
6 Pin means OLED but the controlboards hast v.20 printed on it and there is no V2 OLED-Version of the firmware.
What version of your firmware should I use? :)

Thanks!

![IMG_8293](https://user-images.githubusercontent.com/79941274/185934066-2c1100e3-a0cd-4dbc-9540-73abdadc47ec.jpg)
![IMG_8295](https://user-images.githubusercontent.com/79941274/185934073-8e2aabb3-3b33-422d-8239-9e3d0b306071.jpg)

**Comment by deividAlfa** [comment]
Hi, looks like a v3... Slightly modified, but same layout, ksger does this all the time!

**Comment by kinoX51** [comment]
ok, thanks! Do you think it's safe to flash v3 or can I help you with anything to verify that?

**Comment by deividAlfa** [comment]
There's nothing that could go wrong if using the wrong firmware, it just won't work.
Try v3 right away!

**Comment by deividAlfa** [comment]
Closing, re-open if having any issues.
