### ISSUE TITLE
FYI

### ISSUE THREAD

**Issue by koendv** [deividAlfa/stm32_soldering_iron_controller#32]
FYI. Quicko T12-958 running Arduino.

![IMG_20220916_132433](https://user-images.githubusercontent.com/2753612/190629109-6ffed1fb-77ca-49a2-9d4f-e1f01e9d4a4b.jpg)

**Comment by deividAlfa** [comment]
Yes, there's MM32 datasheet after all, anyone can fork this proyect and spend time porting it to that mcu.
