### ISSUE TITLE
Ksger SMD Rework Station

### ISSUE THREAD

**Issue by DJ-URAN** [deividAlfa/stm32_soldering_iron_controller#35]
Hi! I have smd rework station hot air gun by Ksger and it have 1.06 firmware.
I see on your github 1.1 version firmware, as original firmware. What the difference between theese versions and could i flash 1.1 instead my own 1.06?
Also i want ask, is it possible to change colding temperature to 50° instead of 100° (when i put gun on stand or push off button on backside of station)?
Thank you!

**Comment by deividAlfa** [comment]
Hot air station is not supported, anyways I have no idea, I don't have any ksger, those files are backups found on Internet.
Modifying a binary firmware is a very complicated task, so not possible, at least not for me.

You'd better ask those questions here:
https://4pda.to/forum/index.php?showtopic=1009098
