### ISSUE TITLE
iron profile auto detect

### ISSUE THREAD

**Issue by FrankHovis** [deividAlfa/stm32_soldering_iron_controller#49]
I notice there's a menu option to Set which iron profile (T12, C210, C245) is used. Is there any way for the firmware to detect which type of iron is plugged in? These controllers https://www.aliexpress.com/item/1005002380823696.html use a resistor to identify the iron used.

**Comment by deividAlfa** [comment]
If this was custom hw, it would be pretty easy, but existing controllers don't have any way of detection.

Long time ago I thought on adding a resistor to the shake pin, but none are connected to ADC inputs.

Remember this project aims to replace the original fw, without heavy hw modifications, avoiding breaking original fw compatibility or risking ruining the board by unexperienced hands.

**Comment by deividAlfa** [comment]
These controllers don't use NTC at the handle:
![H709935d4b81d40928372f1e572061948U jpg_640x640q90](https://user-images.githubusercontent.com/48562135/224492240-620cfc76-3658-416f-87a5-4046b62b4470.jpg)
