### ISSUE TITLE
ksger with c245

### ISSUE THREAD

**Issue by labotecno** [deividAlfa/stm32_soldering_iron_controller#52]
hello i need a shematic to connect c245 with ksger v2 [https://github.com/deividAlfa/stm32_soldering_iron_controller/blob/master/BOARDS/KSGER/v2/Schematic/Board.jpg](url)
can you help me ?

**Comment by deividAlfa** [comment]
Look here:
https://www.eevblog.com/forum/reviews/stm32-oled-digital-soldering-station-for-t12-handle/msg4735031/#msg4735031

Your board is slightly different, R11 is placed a little bit upper, but it's the same modification.

**Comment by labotecno** [comment]
thank you , and the connection from gx12 ? i have 3 wire from a case toor T12-11 and i want to adapt ![https://es.aliexpress.com/item/4000270557037.html?spm=a2g0o.order_list.order_list_main.112.7c56194dPQmPKA&gatewayAdapt=glo2esp](url)
i have ntc read low

**Comment by deividAlfa** [comment]
Keep reading that eevblog thread, there's plenty of information in the last pages.
Please note that this is not free personal support, only for firmware issues, use the forum instead!

**Comment by labotecno** [comment]
every thing is ok now you can close this thread
