### ISSUE TITLE
Handskit, ic stm32 103

### ISSUE THREAD

**Issue by ascarons22** [deividAlfa/stm32_soldering_iron_controller#57]
First thank you for your work, I would like to ask you what would be the correct firmware for me, it is a handskit, with stm32f103, but it is not clear to me which firmware to use, since my pcb is different Of those shown in photos, ¿could you tell me which one to use?. Gracias por adelantado

**Comment by ascarons22** [comment]
HW 2.1s,SW2.11
![IMG20230609123304](https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/23247285/72bb699b-e1ad-4859-ae17-3b58ff88241e)

**Comment by deividAlfa** [comment]
Hi, use Ksger v2 firmware.
Reopen the issue if required,
Regards

**Comment by ascarons22** [comment]
Thank you, thank you very much. Greetings
