### ISSUE TITLE
GD32 ADC issues -- possible fix

### ISSUE THREAD

**Issue by HumbleDeer** [deividAlfa/stm32_soldering_iron_controller#59]
Hi!

I saw you had issues with the GD32 clone chips regarding the ADC.

Tronxy, a 3D-printer manufacturer, also uses GD32 (GigaDevice) parts on their boards and have documented a change to the Arduino libraries, necessary to make the ADC work properly.

Perhaps this is of use to this project as well? While the STM32 soldering iron controller firmware isn't based on Arduino, it looks like a fairly trivial thing to implement (being a bitwise shift on ADC values) on CubeIDE based on the Arduino changes. 

https://github.com/tronxy3d/F4xx-SIM480x320/blob/firmware/README.md#faq
See the FAQ section, point 2.2:

> When GD32 series chips are confirmed, you need to modify:
> In the "platformio.ini" file, find Section [my_board], where there is a "DMCU_TYPE=0", change it to "DMCU_TYPE=4"
> 
> In the platformio installation directory, find the function uint32_t analogRead(uint32_t ulPin) in the .platformio\packages\framework-arduinoststm32\cores\arduino\wiring_analog.c, Add some code under the statement "value = adc_read_value(p, _internalReadResolution)",like this:

```c++
...(truncated)
uint32_t analogRead(uint32_t ulPin)
{
	uint32_t value = 0;
		#if defined (HAL_ADC_MODULE_ENABLED) && !defined (HAL_ADC_MODULE_ONLY)
			PinName p = analogInputToPinName(ulPin);
			if (p != NC) {
				value = adc_read_value(p, _internalReadResolution);
// ---------- START Tronxy code ----------
				#if MCU_TYPE == 4 //If MCU is GD32
					#if ADC_RESOLUTION == 12 // 12bit
						// Do nothing
					#elif ADC_RESOLUTION == 10 // 10bit
						value >>= 2;
						value &= 0x03FF;
					#elif ADC_RESOLUTION == 8 // 8bit
						value >>= 4;
						value &= 0x00FF;
					#else
						#error "The adc does not support the resolution"
					#endif
				#endif
// ---------- END Tronxy code ----------
				value = mapResolution(balue, _internalReadResolution, _readResolution);
			}
...(truncated)
```

**Comment by deividAlfa** [comment]
The problem is different, caused by the use of the ADC  in conjunction with the DMA.
Basically the order of the samples drift or misaligns.
So you get 
1 2 3 4 stop
Then
2341 stop

And so on. Similar to explained here:
https://wiki.luatos.com/chips/air32f103/switchFromSxx.html#adc-dma

However, I'm done with clones and I won't spend any more time trying to fix them.
