### ISSUE TITLE
Shake wake sensitivity too high

### ISSUE THREAD

**Issue by zyonee** [deividAlfa/stm32_soldering_iron_controller#6]
Hi!

I'd like my device to stay in sleep mode until I actually move the soldering pen, so I set it to "Wake mode: SHAKE". This works, but it works a bit too well. If I just nudge my desk very gently, the sleep is interrupted. Is there any way to decrease the shake sensitivity? Maybe some debounce logic could help?

**Comment by deividAlfa** [comment]
Set Shake to Standby, and button to All.
That way only the button will wake from sleep.

**Comment by deividAlfa** [comment]
As the name suggest, it detects changes, not states.
When you move the handle it will generate hundreds of small pulses. 
If your handle is so sensitive, just set Shake to Standby, and button to All, that way only the button will wake It up from sleep.

**Comment by deividAlfa** [comment]
If your handle is so sensitive, just set Shake to Standby, or disable it, leaving the button for that.
The Shake input will be used anyways when the station is running, keeping it from entering low power modes, but once it entered sleep / standby, it won't wake it up.

Btw a mercury switch works a lot better.

**Comment by zyonee** [comment]
Thanks for the feedback! I'll look into getting a mercury switch. Thanks for this great firmware, keep it up!

**Comment by deividAlfa** [comment]
I added a shake input filtering option, can be enabled in the menu.
It's time-based, ignoring too fast or too slow changes.
For now, it only can be enabled and disabled, but not tuned, I don't think it needs so, wel'll see how it goes.

Stay tuned for the next build!

**Comment by zyonee** [comment]
Awesome! Thank you!

**Comment by zyonee** [comment]
I've played around with the minimum and maximum tick values. Seems like your default is still too sensitive for my device. Changing it to <200 || >400  seems to be golden for me. I have to tap my desk in the exact right rhythm to exit sleep/standby, and if I pick up my soldering pen, all it needs is a bit of a shake (which is what shake wake implies). Good work!

**Comment by deividAlfa** [comment]
Nice! Closing this then.
