### ISSUE TITLE
RTC (Non-working features)

### ISSUE THREAD

**Issue by HumbleDeer** [deividAlfa/stm32_soldering_iron_controller#60]
> Realtime clock - there's very little screen space. Use it for what matters, instead for showing a clock!

Does this mean realtime clock is not implemented at all? Or is it just not shown? 

I'd be interested in having it at least on my screensaver or implementing an option to replace something else with the clock, perhaps through a menu option. I'm not an STM32 developer but do have C++ experience. If the RTC is implemted or functioning otherwise, I'd be happy to give it a shot on UI. :)

**Comment by deividAlfa** [comment]
Not implemented, nor it will, sorry.
