### ISSUE TITLE
Test on t9 tips for fm2023 tweezers

### ISSUE THREAD

**Issue by Wsander1** [deividAlfa/stm32_soldering_iron_controller#61]
Has anyone tested the t9 tips for the hakko fm2023. I did hook a t9 tip to my station. And noticed that temps jump around on other clones of hakko. It would be nice to include t9 tips as part of the programming into these stations. So someone could hook up fm2023 tweezers to these stations with accurate temps. The t9 work but the temps jump around. They do work normally. Just no way of telling accurate temps. I have a pair of fm2023 that has a issues where only one side works on my hakko station. That is because of the cold temp 10k ntc sensor that's located within the tweezers. If that sensor is broken the original hakko station will error. But hooking the fm2023 to a clone would bypass those issues and they would work normally. Just need a bit of time tuning in the firmware so these stations would accept hakko t9 tips. Any info would be awesome.

**Comment by deividAlfa** [comment]
Closed as nobody answered in a very long time.
