### ISSUE TITLE
Custom Boot Logo Help

### ISSUE THREAD

**Issue by Doyle4** [deividAlfa/stm32_soldering_iron_controller#63]
Hello, I have changed the boot screen image in the Pictures folder, but when compiled via the .bat file the default is still shown.
How do I change it to a custom one please? :)

**Comment by deividAlfa** [comment]
Hi, read this:
https://www.eevblog.com/forum/reviews/stm32-oled-digital-soldering-station-for-t12-handle/msg4600576/#msg4600576

**Comment by Doyle4** [comment]
Thank you, will take a look at thanks.
