### ISSUE TITLE
Not sure what I'm doing wrong.

### ISSUE THREAD

**Issue by Doyle4** [deividAlfa/stm32_soldering_iron_controller#64]
I compiled a file yesterday fine with Building_script.bat, I had to choose my board (3) then option 1 to copy files, re-open the .bat and then select 3 and 3 again which worked fine. Today when I run the .bat file it says Compiling:Display, then shows a red error - 1 but can't find what the error is.
I deleted the Source folder and unzipped a new one and tried again with same issue.
I have tried copying the 4 files from the V2 folder needed and paste at root, same error, I have also tried without moving the files and relying on the .bat file to move with same error.
Im not very good with coding so I apologise, like I say, yesterday built one fine and flashed, today no luck.

Any help/tips be great.
Love the firmware.

Thanks.

**Comment by deividAlfa** [comment]
Sorry I can't help much with the provided information.

 - Only use CubeIDE 1.12.1, nothing else. Don't have multiple versions installed.
 - The procedure is simple, just download the code, extract somewhere and run building script, choosing your board and then option 3 (Copy/run MX/compile).
 - If you're not modifying anything, then simply download a release binary.
 
You might import the project into CubeIDE after choosing option 2  then compiling there to see the errors. This is shown in the video, skip the manual file coying step.

I guess you're trying to change the boot screen and did something wrong...?

**Comment by Doyle4** [comment]
Thanks for replying.
CubeIDE 1.12.1 installed but also Utility for flashing the file to STM32.
That was the procedure I did first time to work but no longer does, unmodified source/modified source.
I changed the boot_screen.c, using an online converter to change image to code.

Thanks again.

**Comment by deividAlfa** [comment]
Doesn't work even when deleting the entire folder and using a new base?

**Comment by Doyle4** [comment]
Tried with deleting folder, and tried with re downloading source.
Will take a good look again before coming back, thanks again :)

**Comment by Doyle4** [comment]
Tried making a new user and still no luck, uninstalled CubeIDE, rebooted, reinstall, no luck.
Im going to give up trying as I have no clue what I have done wrong lol.
THanks for your help though!

**Comment by deividAlfa** [comment]
What happens when you choose only option 1?
Then import the project into cubeIDE as shown in the video.
What's your system language?

**Comment by Doyle4** [comment]
Not currently at my Windows machine, but will try this when I can and update.
English (International I think, Im in UK and never choose the US English).

**Comment by deividAlfa** [comment]
Hmm now it's also failing for me!

**Comment by deividAlfa** [comment]
Fixed!
For some reason CubeIDE rejected to build it, arguing the project already existed in the workspace, though it didn't!

Delete C:\Users\YOUR_USER\STM32CubeIDE\workspace_1.12.1\\.metadata folder.

Run the script again, should work now.
If still failing, delete the entire workspace folder.

![image](https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/48562135/5aa11a12-d161-4c58-88ee-130ce6de549b)

**Comment by Doyle4** [comment]
Amazing, will try this and fingers crossed confirm also.
Once again, thank you!

**Comment by Doyle4** [comment]
Amazing! Worked for me also.
Thanks for your time and help.

**Comment by deividAlfa** [comment]
Nice! Closing the issue as it's solved!

**Comment by Doyle4** [comment]
![logo](https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/65953502/7c28e5c7-dfbf-4248-b236-3aea59e3f4fe)
[boot_screen.c.zip](https://github.com/deividAlfa/stm32_soldering_iron_controller/files/12504908/boot_screen.c.zip)
Custom Boot screen if anyone else would like it, not to everyone's taste I know :)

**Comment by deividAlfa** [comment]
Haha nice!

**Comment by synthkeywizard** [comment]
> ![logo](https://user-images.githubusercontent.com/65953502/265235275-7c28e5c7-dfbf-4248-b236-3aea59e3f4fe.JPEG) [boot_screen.c.zip](https://github.com/deividAlfa/stm32_soldering_iron_controller/files/12504908/boot_screen.c.zip) Custom Boot screen if anyone else would like it, not to everyone's taste I know :)

Can you make a photo how it looks at your station?

**Comment by Doyle4** [comment]
A soon as I can I will.

**Comment by Doyle4** [comment]
![IMG_1802](https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/65953502/30b829b5-41b8-4852-b1a7-59edbec40cc4)

**Comment by deividAlfa** [comment]
In white: 

![IMG_20230903_123722](https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/48562135/efb414ac-5fa9-49eb-bab7-467fb7a37943)

**Comment by Doyle4** [comment]
Prefer it in white, nice!
