### ISSUE TITLE
Add support for ksger v3.3 board

### ISSUE THREAD

**Issue by LynxChaus** [deividAlfa/stm32_soldering_iron_controller#67]
Please add support for v3.3 board:

CPU: STM32F103CBT6

OLED display connected to PINs: 25 (PB12) SCL, 26 (PB13) SDA
Encoder - 38 (PA15) KEY, 39 (PB3) Pin A, 40 (PB4) Pin B
UART? - 42 (PB6), 43 (PB7) (unpopulated 3-pin header near buzzer)
10 (PA0) - SCL (Pin1 IC CIEAH marking, some AT42CXX in SOT23-5 package)
11 (PA1) - SDA (Pin3 IC CEIAH marking)
Tip Temp - 12 (PA2)
Buzzer - 13+14+15 (PA3+PA4+PA5)
Shake - 16 (PA6)
NTC - 17 (PA7)
Heater PWM - 18 (PB0)
VIN Monitor - 19 (PB1)
![ver3 3-board](https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/4587687/45d18bae-8b54-43f1-826b-021bf4894c9f)

**Comment by deividAlfa** [comment]
This seems normal v2 hardware, so try that.

Seems to be just another board revision with the same actual connections as any other v2-based hardware, check the schematic:

https://github.com/dreamcat4/t12-t245-controllers-docs/blob/master/controllers/stm32-t12-oled/v2.1s-and-Ve2.1S/KSGER%20STM32%20Ver2_1S%20schematic%20rev%202_floobydust.pdf


Some parts can change between revisions, like the voltage regulator or the amplifier, but regarding the firmware this makes no difference, the stm32 connections are the same.

These are all the same thing, just as yours:

https://github.com/dreamcat4/t12-t245-controllers-docs/blob/master/controllers/stm32-t12-oled/v2.1s-and-Ve2.1S/r1/KSGER%20STM32%20OLED%20controller%202-1S%20closeup1.jpg

https://github.com/dreamcat4/t12-t245-controllers-docs/blob/master/controllers/stm32-t12-oled/v2.1s-and-Ve2.1S/r1/back.jpg

https://github.com/dreamcat4/t12-t245-controllers-docs/blob/master/controllers/stm32-t12-oled/v3.0-and-v3.1/r1/back.jpg

https://github.com/dreamcat4/t12-t245-controllers-docs/blob/master/controllers/stm32-t12-oled/v3.0-and-v3.1/r2/20200608_014712.jpg

**Comment by czullo** [comment]
I can confirm that this is V2 hardware, i got same on my Quecoo T12-955 and im running on this KSGER_v2_OLED firmware with no problems.
![1698754564634](https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/13511496/ee92d0da-ed3a-4c97-83a1-4e108194f879)

**Comment by deividAlfa** [comment]
Closing then!

**Comment by LynxChaus** [comment]
Mention this board in docs, please.

**Comment by deividAlfa** [comment]
No need to, this simple rule still applies:
- 4 pin oled: V2.
- 6-7 pin oled (Except old Quicko) : V3.

Simple as that!

**Comment by LynxChaus** [comment]
Simple for you, who know schematic of gazzilon this boards. For someone, who bought this board - find in ```$(searchengine)``` ```$(boardname)``` is better than tracing connections from CPU to peripherals. For me this cost is two hours. Grr.

**Comment by LynxChaus** [comment]
Well, flashed KSGER_v2_OLED, it's run but report "VOLTAGE LOW" and "NTC READ LOW". 
![T12-display](https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/4587687/64f16170-ade5-4bd9-9932-cdeca93dec8e)
What I'm doing wrong?

**Comment by deividAlfa** [comment]
- Power it with the 24V PSU, not from the ST-Link.
- NTC is in the handle, connect it.

**Comment by deividAlfa** [comment]
Will try to add more board pictures, but last time I has some issues and wasn't able to do so, GitHub blocked the uploads.

**Comment by LynxChaus** [comment]
Yes, my bad, I'm run it from ST-Link power. 
Powering from 24v power supply is properly report input voltage, but NTC read -5.0 degrees. Switching NTC detect ON/OFF from Iron menu don't help. Only set manually resistance to 10K and enable "NTC detect" - show temperature                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 +38.x degree (wrong). Switching OFF "NTC detect" - show temperature -99.9 degree.

Well, found inadequate 470K NTC in handle, replaced it to 10k NTC ... and temperature now +5 degree, when NTC resistance is 11.08k (+22 degree). Playing with beta value don't help. Switching PullUp to Down - show temperature +44 degree.
What is wrong here?

**Comment by deividAlfa** [comment]
Leave 10K value for NTC. It's pullup, 4k7.
Or simply disable NTC so it uses internal stm32 sensor.

**Comment by LynxChaus** [comment]
Aha, understand. Reverted back pull resistance to 4.7k, adjusted beta and now it show normal temperature.
Thnx!

**Comment by deividAlfa** [comment]
I hope this fixes any doubts when identifying the boards:
https://github.com/deividAlfa/stm32_soldering_iron_controller/blob/master/Readme_files/boards.md

**Comment by LynxChaus** [comment]
Great. Write versions (2.1s, v3.3 and so) after "Ksger v2" - for search engines.

**Comment by deividAlfa** [comment]
Nope, Ksger boards naming is a mess, people only have to check the [Readme](https://github.com/deividAlfa/stm32_soldering_iron_controller#readme)!
Also, some boards are sold under different brands.

If reading the [Compatibility](https://github.com/deividAlfa/stm32_soldering_iron_controller#compatibility) section is hard, well, this FW requires a minimum IQ of 1!

**Comment by deividAlfa** [comment]
Closed, not an issue. Just read!
