### ISSUE TITLE
More convenient control for standby/sleep via an encoder.

### ISSUE THREAD

**Issue by vlk3ru** [deividAlfa/stm32_soldering_iron_controller#68]
Dear author, your software is excellent. I flashed it for my station KSGER  PCB hw: Ve2.12S. But it would be very convenient to send the station to Stanby/Sleep mode by simply pressing the encoder key instead of showing the heating graph. Can you make this optional setting ?

**Comment by deividAlfa** [comment]
Good idea. I barely have any time to spend in this project, today was a lucky day!
https://github.com/deividAlfa/stm32_soldering_iron_controller/releases/tag/v1.10.6

**Comment by vlk3ru** [comment]
I updated my KSGER station to 1.10.6 firmware. Everything works great. Management has become very convenient. Thank you very much !

**Comment by deividAlfa** [comment]
Enjoy!

**Comment by Doyle4** [comment]
Amazing! I was looking for an option to do this, make sense now why I couldn't find it. 
Thanks :)

**Comment by synthkeywizard** [comment]
If it was user-configurable from setup menu - it would be a great improvement.

**Comment by Doyle4** [comment]
Love this firmware, but I couldn't get use to putting in standby/sleep click rotating, would either go to graph or lower temp haha, this is a huge improvement for me!

**Comment by deividAlfa** [comment]
Sorry, no option will be added for this, this will be the new setting from now!
Setpoint adjustment, sleeping and menu are the top priority actions, so they got the easiest gestures.
The graph screen is absolutely useless, only a fancy thing, so it should receive the lowest priority.

**Comment by serisman** [comment]
Thank you for making this change!  This fixes one of minor annoyances I was having with this excellent firmware.

One thing I noticed is that I have to rotate the encoder to exit sleep mode instead of just pressing the button.  Is this on purpose, or an oversight?

**Comment by deividAlfa** [comment]
Yes, accidental clicking (Like a faulty contact or unsteady hand) would be a mess, resuming run mode unintentionally.
You have to rotate only one step, so the setpoint won't even be shown or modified.

**Comment by serisman** [comment]
Ok, that makes sense.  Thanks for the response.

**Comment by Doyle4** [comment]
Installed and working as stated by others, great update feature!
