### ISSUE TITLE
Question not an issue.

### ISSUE THREAD

**Issue by Doyle4** [deividAlfa/stm32_soldering_iron_controller#71]
Im still currently on 1.10.6 and was about to update to 1.11.0 and spotted a newer update today.

1.11.0 mentioned it will wipe all data which is fine, but 1.11.1 says data will stay, is this only for people who update from 1.11.0 to 1.11.1 or will updating from 1.10.6 > 1.11.1 keep my current settings? 
Like I say, I honestly don't mind it wiping, just wondering before I do the update and to have tip calibration tool at hand for when I do update.

Thanks again!

**Comment by deividAlfa** [comment]
It clearly says ”It won't wipe data coming from 1.11.0". Only from 1.11.0.

**Comment by Doyle4** [comment]
I apologise for having learning difficulties and not understanding it properly, Jeez....
