### ISSUE TITLE
sleep problems

### ISSUE THREAD

**Issue by daohuaxiang4** [deividAlfa/stm32_soldering_iron_controller#73]
在固件中，我希望在手柄中添加一个倾斜开关，以实现低功耗，类似于ksger原始固件的低功耗模式进入睡眠状态。我没有特定的睡眠支架来睡觉，在低功耗模式下总是把烙铁倒置。

**Comment by deividAlfa** [comment]
You have stand mode for that.
Read the operation manual, there it talks about this.
You should discomnect the shake pin from the board connector, and wire it to the handle stand.
When the handle is put into the stand, that wire is shorted to ground, either by the handle itself or a switch.
