### ISSUE TITLE
Profile for AD597 + GOOT RX-80HRT ?

### ISSUE THREAD

**Issue by vlk3ru** [deividAlfa/stm32_soldering_iron_controller#74]
I use KSGER V2.1 stations with an AD597 amplifier and GOOT RX-80HRT+RX-85HRT tips with a K-type thermocouple inside these cartridges. Which profile should I use out of the three Hakko T12 / JBC C210 / JBC C245 ?

**Comment by deividAlfa** [comment]
This is not an issue, but DIY, use eevblog forums in the future.
How would I know? This nowhere standard, probably none!
If that amplifier outputs 10mV/°C, at 450°C it'll be 4.5V, the stm32 can't measure that, it's 3.3V max.
You'll need to use a resistive divider at the output, like Amplifier -> 1k -> stm32 -> 1k8 -> gnd.
Then 5V output will be 3.2V at the stm32.
Ensure the voltage never exceeds 3.3V or you will damage it.

Then choose any profile, open calibration menu, insert tip now (Not before), open settings and manually adjust 250 and 400°C steps while measuring the tip temperature.
Then save and run the automated calibration.

**Comment by vlk3ru** [comment]
I immediately removed the stock amplifier in 2019 and instead installed a custom AD597 thermocouple amplifier and a goot pen with RX-8xHRT cartridges. This all works great with KSGER firmware 2.10 and even better with your firmware 1.10.6. Everything is fine. Thank you for your firmware. My question is different: Which profile should I choose in your firmware? There are only three profiles in the firmware. And my case is not. Maybe it would be better to add a fourth user profile? Having the name "USER" for example ? It's just a question.

**Comment by vlk3ru** [comment]
![ksger_vlk-ad597](https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/150119370/4b48e0ab-ec36-47fc-9299-09feccf40d66)

My diagram is for clarity.

**Comment by vlk3ru** [comment]
Question about this:

gui_strings.c :
char * const profileStr[NUM_PROFILES] = { "T12", "C245", "C210" };

Do you think it is possible to add a fourth profile ?

**Comment by deividAlfa** [comment]
It could be possible but lots of other changes will be needed everywhere, I'm not doing that sorry.

Better you rename an existing profile name in:
https://github.com/deividAlfa/stm32_soldering_iron_controller/blob/master/Drivers/graphics/gui/screens/gui_strings.c#L1303

The default tip names are here:
https://github.com/deividAlfa/stm32_soldering_iron_controller/blob/master/Core/Src/settings.c#L633

The default calibration is in your controller type profile, BOARDS/KSGER/x/STM32F1xx/Core/Inc/board.h

Modify as required and compile for your own.

**Comment by vlk3ru** [comment]
Thanks for the answer.

**Comment by deividAlfa** [comment]
Powering the amplifier with 24V is dangerous,  
if anything goes wrong, even with the resistor divider, the stm32 will get 15V and probably fry.

Put a 3.3V zener in parallel with the 1K8 resistor!

**Comment by vlk3ru** [comment]
Thank you very much !
I will definitely take your recommendations into account and change the circuits of my devices.

**Comment by deividAlfa** [comment]
Also, there's no memory left in 10KB devices (STM32F101), so another profile would not fit.
A STM32F103  (20KB) would, but I have to keep compatibility with all.

**Comment by vlk3ru** [comment]
Ok.
In addition to the 3.3V zener diode, according to the AD597 datasheet, +5V power supply is possible instead of +24V.

**Comment by vlk3ru** [comment]
> Also, there's no memory left in 10KB devices (STM32F101), so another profile would not fit. A STM32F103 (20KB) would, but I have to keep compatibility with all.

I just used Profile T12. Just without thinking. But apparently it is possible to use any profile for calibration and work in my case.
