### ISSUE TITLE
Question: FW compatibility

### ISSUE THREAD

**Issue by vookimedlo** [deividAlfa/stm32_soldering_iron_controller#75]
Hello,

I have just bought the KSEGR T12 and have the following controller board inside. I cannot find this board layout on any forums so I ask directly. Can I use your FW with this board?

Thank you.

<img width="444" alt="image" src="https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/2312301/d20485d2-6c8a-48bb-b18a-de4658145aa0">

**Comment by vlk3ru** [comment]
This is probably KSGER HW version 2.0 .

FW : https://github.com/deividAlfa/stm32_soldering_iron_controller/releases/download/v1.11.2/KSGER_v2_OLED.zip

**But problem: STM32F103C8T6 - has ONLY 64Kb of flash !**
Need resold to STM32F103CBT6 - has 128Kb of flash memory.

**Comment by vlk3ru** [comment]
![stm32_t12_oled_v2 0](https://github.com/deividAlfa/stm32_soldering_iron_controller/assets/150119370/240d3c25-5036-4cb8-8bfe-60b26077b262)

**Comment by deividAlfa** [comment]
Another V2 yeah. Read the Readme for the 64kb issue.

**Comment by vookimedlo** [comment]
Thanks, will try to replace the MCU with STM32F103CBT6.

**Comment by deividAlfa** [comment]
There's no need to replace it, read [`Compatibility`](https://github.com/deividAlfa/stm32_soldering_iron_controller?tab=readme-ov-file#compatibility)! 64KB devices actually have 128KB!

**Comment by vlk3ru** [comment]
> There's no need to replace it, read [`Compatibility`](https://github.com/deividAlfa/stm32_soldering_iron_controller?tab=readme-ov-file#compatibility)! 64KB devices actually have 128KB!

Sorry, I didn't know about this.
